### PR TITLE
Fixing the IDLType to Candid to IDLType round-trip test

### PR DESCRIPTION
**Pull request by tglaeser**
I assume you already noticed all of this, but I wanted to report my findings:

I'm pretty confident that the `toString` methods need to stay as proposed here, before a `IDLType.Id` became a `IDLType.Primitive.Null` which is an error; on the surface the string representation looked the same but the types simply didn't match.

I don't quite understand the use of `IDLGrammar#ids` in this context, but this change will result in more errors with `CodeGenerationTest`.

And then there are errors
```
e: Canister1.kt: (50, 42): Unresolved reference: greet
e: Canister1.kt: (50, 42): Unsupported [literal prefixes and suffixes]
```
Could it be that those are rather a problem with the transpiler implementation instead of the type system? I'm completely unfamiliar with this part of the code base yet.

### CODE REVIEW

**Comment by seniorjoinu** [comment]
> I don't quite understand the use of IDLGrammar#ids in this context, but this change will result in more errors with CodeGenerationTest.

The `ids` list is a hack needed for variant and record short field types. Imagine these two examples
```
variant { A; B; C }
```
and 
```
type A = int;
type B = int;
type C = int;

record { A; B; C }
```

In the first example A, B and C are `name values` of variants. After parsing they go into `IDLFieldType(variantName, IDLType.Primitive.Null)`.
In the second example A, B and C are `types` of positional record fields. After parsing they go into `IDLFieldType(null, recordFieldType)`.
Check the `Field Type` section of the parser.
This inconvenience comes from: a) candid specification; b) the fact that the child parser doesn't know the type of his parent.
UPD: yes, I know this doesn't solves the problem completely, but for 0.1 it seemed okay to me. We can solve this when the `pFieldType` will know which parser is his parent (then it can decide should it apply rules for variants or for records). Gonna make an issue for that.

`CodeGenerationTest.kt` generates kotlin code out of the source candid strings and then __compiles them on the fly__, to check if the generated code was at least syntactically valid. So, the error you get is telling you, that changes you've made broke the transpiler and now it generates invalid code. 
To see generated code and figure out what's exactly went wrong you can check the temporary file with it (in your example -  `Canister1.kt`). It's path should be seen from the stack trace of the error.

P.S. seems like quotes in `TextVal` are not working well - after code generation you get something like this
```kotlin
class MainActor(bla: Bla) {
  val "greet" = AnonFunc0(""greet"", bla) // <-------- another quote pair here
}
```

**Comment by tglaeser** [comment]
> The `ids` list is a hack needed for variant and record short field types. Imagine these two examples
> ```
> variant { A; B; C }
> ```
> and
> ```
> type A = int;
> type B = int;
> type C = int;
> 
> record { A; B; C }
> ```
> In the first example A, B and C are `name values` of variants. After parsing they go into `IDLFieldType(variantName, IDLType.Primitive.Null)`.

Thanks for taking the time to explain this. This then means that this needs to be corrected in the test itself: The test assumed the fields within the variant were of type `IDLType.Id` and failed as the returned fields were of type `IDLType.Primitive.Null` (even as the string representation looked the same). I'll fix this.

**Comment by tglaeser** [comment]
After my last commit there is exactly one failing test left from `IDLGrammarSpecification`: `positive single service with parameters peers`. This could be problem with the `IDLGrammar#ids` hack or an issue with the test itself.

The string representation looks again the same:
<pre>
record {
    preimage: vec nat8;
    image: vec nat8;
};
type List = opt record {
    Key;
    <b>List</b>;
};
type Bucket = List;
type List_2 = opt record {
    text;
    <b>List_2</b>;
};
service : {
    "peers": () -> (List_2);
}
</pre>
However the test expects field `List`/`List_2` to be of type `IDLType.Id` while it is in fact of `IDLType.Primitive.Null`. The IDL defines type `List`/`List_2` as a record containing a field named `List`/`List_2` which is of what type? It must be `IDLType.Primitive.Null`, otherwise the field in the record would have a circular dependency, right?

**Comment by seniorjoinu** [comment]
Thank you for your effort.

> However the test expects field List/List_2 to be of type IDLType.Id while it is in fact of IDLType.Primitive.Null

This is not right. In this case, List/List_2 should be of type IDLType.Id. Circular dependencies are handled properly here: List is optional record - you can indeed construct such a type.

**Comment by tglaeser** [comment]
Closing this PR; created issue #22 for the remain test failure; will create a new PR for the remaining changes.

**Pull request closed without merging**
